spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${shand.mysql.host}:${shand.mysql.port}/second_hand?characterEncoding=utf8&serverTimezone=UTC
    username: ${shand.mysql.username}
    password: ${shand.mysql.password}
  data:
    redis:
      host: ${shand.redis.host}
      port: 6379
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.onezhan.pojo
  mapper-locations: classpath:/mapper/*.xml
