version: "3.8"

networks:
  aderversa:
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    container_name: mysql-project
    ports:
      - "8888:3306"
    networks:
      aderversa:
        ipv4_address: 172.19.0.2
    environment:
      - TZ=/Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - "../volums/mysql-volum/data:/var/lib/mysql"
      - "../volums/mysql-volum/log:/var/log/mysql"
      - "../volums/mysql-volum/conf:/etc/mysql"
      - "../volums/mysql-volum/mysql-files:/var/lib/mysql-files"
  redis:
    image: redis:6.2.6
    container_name: redis-project
    ports:
      - "6379:6379"
    networks:
      aderversa:
        ipv4_address: 172.19.0.3
  shand:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shand
    ports:
      - "8080:8080"
    networks:
      aderversa:
        ipv4_address: 172.19.0.4
    depends_on:
      - mysql
      - redis
